/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/python-8be4a2579dd84586b915068e475073ee
Title: Python
*/
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const PythonLogo = (props) => {
  const logoRef = useRef()
  const { nodes, materials } = useGLTF('/models/python.glb')
  useGSAP()
  useGSAP(() => {
      gsap.to(logoRef.current.position, {
          y: logoRef.current.position.y + 0.5,
          duration: 1.5,
          repeat: -1,
          yoyo: true,
      })
      gsap.to(logoRef.current.rotation, {
          z: logoRef.current.rotation.z + 0.25,
          duration: 1.5,
          repeat: -1,
          yoyo: true,
      })
  })
  return (
    <group position={[0,5,0]} scale={0.4} {...props} dispose={null}>
      <pointLight intensity={100} position={[0,30, 0]} />
        <mesh
          ref={logoRef}
          geometry={nodes.Python_Python_0.geometry}
          material={materials.Python}
          rotation={[-Math.PI / 2, 0, 1]}
          position={[0, 1, 0.181]}
          scale={[0.19, 0.29, 0.25]}
        />
      </group>  )
}

useGLTF.preload('/models/python.glb')

export default PythonLogo
